### ISSUE TITLE
Password for servers

### ISSUE THREAD

**Issue by hypertexthero** [FloatingOriginStudios/BalsaIssues#24]
**Is your feature request related to a problem? Please describe.**
I would like to host a game for friends only without having random players join.

**Describe the solution you'd like**
The ability to set a password when creating a server.

**Describe alternatives you've considered**
Having a checkbox with the text “Steam friends only” that makes your server visible only to your Steam friends is another possibility.

Thank you for making Balsa! I love it!

**Comment by Moach** [comment]
Should be in the next build
