### ISSUE TITLE
When grabbing the root part (and all attached parts) the player cant rotate/manipulate using the keyboard when its indicated that it can be

### ISSUE THREAD

**Issue by anth1256** [FloatingOriginStudios/BalsaIssues#25]
**To Reproduce**
Steps to reproduce the behaviour:
1. Create a new craft
2. Pick a first part
3. Grab Part
4. Try to rotate according to the cheatsheet on the right

**Expected behaviour**
Root Part (and all attached parts) should rotate with the keyboard like non root parts do.

**Screenshots**
![20210831103502_1](https://user-images.githubusercontent.com/74987984/131415017-443f3a4b-a20b-4505-a7a4-0cb8cb531a63.jpg)

**Comment by PsykomantaBrain** [comment]
Confirmed. The Rotate tool does allow rotating the root part, so I guess there's no reason why it shouldn't be allowed with the place tool as well.

**Comment by PsykomantaBrain** [comment]
Ok, removed the rotation restriction from the root part. Seems to be ok, although the aerodynamics overlay does go nuts a little bit. That's another story though.

**Comment by anth1256** [comment]
Excellent.
