### ISSUE TITLE
On loading my (horrible) plane model, the tool defaults to "Caption" with a white square, instead of a default.

### ISSUE THREAD

**Issue by pjpei** [FloatingOriginStudios/BalsaIssues#3]
**Describe the bug**
When loading into the workshop with my specific plane model, the default selected mouse action tool is a white square titled "Caption", instead of a the placement tool.

**To Reproduce**
1. Start the game
2. Click on "Build & Fly"
3. Click on Workshop
4. Select my awful plane model
5. Select Wirraway Bay
6. Click "Go"
7. The selected tool is now a white square titled "Caption"

**Expected behavior**
I would expect the tool have a sensible default, perhaps "Place"?

**Screenshots**

**Desktop (please complete the following information):**
Windows 10 x64

**VR (please complete the following information):**
No VR

**Additional context**
This happens whether I start the game and directly load the model, or load the model after quitting the workshop and loading the model again.

I attached a screenshot.  I'm not sure where to upload the logs, it has some nullpointerexceptions.

![tool_says_caption_instead_of_place](https://user-images.githubusercontent.com/25793978/131184131-12e8d70a-0469-4923-ab55-f1f0a7afaa98.png)

**Comment by PsykomantaBrain** [comment]
Could you share the craft file also?

**Comment by pjpei** [comment]
Of course, where can I find it?

**Comment by pjpei** [comment]
[AIDSPlane.zip](https://github.com/FloatingOriginInteractive/BalsaIssues/files/7069287/AIDSPlane.zip)

**Comment by PsykomantaBrain** [comment]
hm, tried loading the vehicle here, and it seems to have loaded fine.  No errors at all, and the craft file appears ok, not corrupted or anything.

Was this happening every time you loaded the game?

**Comment by pjpei** [comment]
I tried a few combinations and it seems it's loading correctly now?  I'm trying to see what I could have done to break it, but I'm unable to reproduce the issue.  It seems to be a once-off bug, but will let you know if I encounter it again.

**Comment by PsykomantaBrain** [comment]
I think whatever happened, was possibly not actually related to your vehicle and the workshop. 

Ok, drop us a line if this pops up again. Closing for now :)
