### ISSUE TITLE
Joystick throttle isn't working correctly

### ISSUE THREAD

**Issue by anth1256** [FloatingOriginStudios/BalsaIssues#39]
**Video Evidence**
Default Settings:
https://youtu.be/fg08N0f9n0A
See how the yellow and the orange arrows arent moving together

New Proposed Settings:
https://youtu.be/bqsH_2eD_Oo

Note how the yellow and orange arrows are almost perfectly moving together.

I recommend changing the default throttle settings to what they are in the video.

The following is a screenshot of what the throttle settings are in the settings that work as per the video
![20210901001340_1](https://user-images.githubusercontent.com/74987984/131500689-b46ee99d-b3fa-4aa4-86a7-149141961783.jpg)

**Additional Information**
I used a Logitech 3D Pro. I am not sure how this will affect other joysticks.

**Credit**
Filip from discord helped with this

**Comment by PsykomantaBrain** [comment]
Uhm, the first video shows the behaviour of an axis with the Relative Axis toggle enabled. That is the expected behaviour for relative axis. The input is used to displace the output. In normal mode, the input directly controls the output (after the calibration settings ofc)

I don't think what you are seeing there is a bug.

**Comment by anth1256** [comment]
The first video is the default settings of the throttle which isn't working well.

Its not the way its working that I am complaining about, its the default settings that I am saying are incorrect.

If the Relative Axis is on for the throttle as a default then its not going to function correctly until the player figures it out

**Comment by anth1256** [comment]
I was just using the XBox controller. I think the default settings for the throttle are made for the XBox and not for lever type throttles like what the Logitech 3D pro has. 

What about a check box and an option for use of either type?

**Comment by PsykomantaBrain** [comment]
So, what you are asking for then is for a new binding preset for non-gamepad type controllers. That I def agree with actually. I didn't get a chance yet to make additional input presets.

This way, there is no need for a check box or anything like that. You'd just select the stick+throttle preset when it asks for it on first load (or when restoring defaults on inputs), and it would be already set with a non-relative axis for throttle.

**Comment by anth1256** [comment]
Yeah. That would be awesome
